# Generated by Django 4.2.2 on 2023-06-10 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0002_language_alter_city_options_alter_city_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=250, verbose_name='')),
                ('company', models.CharField(max_length=250, verbose_name='')),
                ('description', models.TextField(verbose_name='')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='scrapping.city', verbose_name='')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='scrapping.language', verbose_name='')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
    ]
